### PR TITLE
pass options to `benchmark.run`

### PR DESCRIPTION
**Pull request by tunnckoCore**
to support async benchmarking, just found that that was the problem to me that we commenting in some issues before time.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
thanks to https://github.com/kesla/async-benchmark/blob/master/async-benchmark.js#L14 which remind me

**Comment by tunnckoCore** [comment]
hmm, need more review, only this won't fix it, lol i'll check more

**Comment by jonschlinkert** [comment]
thanks for doing this. 

> only this won't fix it, 

k I'll wait for you to update.

**Comment by tunnckoCore** [comment]
hmmm, its interesting and strange, cuz Benachmark.js support two options - defer and async... aaand i thought they both should be true to do async testing.

this ([here](https://github.com/jonschlinkert/benchmarked/blob/master/index.js#L130-L133)) should become
```js
fn: function (deferred) {
  if (deferred && options.defer && options.async) {
    args = args.concat(deferred.resolve.bind(deferred))
  }
  fn.apply(thisArg, args);
}
```
but strangely process exits after running first sample of the bench function.


hm, I'll continue, but thoughts?

**Comment by jonschlinkert** [comment]
> but strangely process exits after running first sample of the bench function.

to confirm, you're saying it only does this with the changes you made? or is that happening before as well?

**Comment by tunnckoCore** [comment]
> only does this with the changes you made

yea yea, when i update to the code above where I forgot to add `defer: options.defer || false`.

now seems it have `done` as last argument of benching function.

**Comment by tunnckoCore** [comment]
@jonschlinkert yea, forgot to mention. it seems it is lil bit tricky. need help

**Comment by jonschlinkert** [comment]
I believe this has been refactored since this pr. closing

**Comment by tunnckoCore** [comment]
:+1: yea, absolutely.

**Pull request closed without merging**
