### PR TITLE
Fix format

### PR DESCRIPTION
**Pull request by elidoran**
Apply the fix from @doowb and tests for both default and override.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Wait, before we do this I'm not sure I agree this is a good approach. I think we need to ensure that options are shallow cloned before we modify an object that might lead to memory leaks. 

I'll add a comment in the code...

**Comment by elidoran** [comment]
How about this instead: make it a prototype function and then override it on the instance when it's provided in the options.

**Comment by jonschlinkert** [comment]
something like?

```
Benchmarked.prototype.format = function(benchmark) {
  if (typeof this.options.format === 'function') {
    return this.options.format.apply(this, arguments);
  }
  return '  ' + benchmark;
};
```
yeah I think that's a better approach

**Comment by elidoran** [comment]
So, the altered version I pushed to this PR right before your comment is good?

**Comment by jonschlinkert** [comment]
I don't really have a preference, but if there is a reason to expose the instance to the user, you'll need to add `.bind(this)` or something. But it's fine as it is if you want to merge and publish. thanks!

**Comment by jonschlinkert** [comment]
thanks, and sorry for the delay!

**Pull request merged**
